config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [:index]
  resources :transactions, only: [:index, :create]
  resources :cards, only: [:destroy]
 
  root "flights#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/transaction.rb
require 'httparty'

class Transaction < ApplicationRecord
  belongs_to :flight
  include HTTParty

  validates :email, presence: true
  validates :amount, presence: true
  
  @@base_uri = 'https://core.spreedly.com/v1'

  def purchase_gateway(token, amt, email, retain)
    purchase_uri = @@base_uri + '/gateways/' + ENV['GATEWAY_TOKEN'] + '/purchase.json'
    response = HTTParty.post(purchase_uri, base_options.merge(
      {
        body: {
        transaction: {
          payment_method_token: token,
          amount: amt,
          currency_code: 'USD',
          retain_on_success: retain,
          email: email
          }
        }.to_json
      }
    ))
    response.parsed_response
  end

  def purchase_external(token, amt)
    deliver_external_uri = @@base_uri + '/receivers/' + ENV['EXTERNAL_TOKEN'] + '/deliver.json'
    response = HTTParty.post(deliver_external_uri, base_options.merge(
      {
        body: {
            delivery: {
              payment_method_token: token,
              url: 'https://spreedly-echo.herokuapp.com',
              headers: 'Content-Type: application/json',
              body: "{ \"amount\": #{amt}, \"card_number\": \"{{credit_card_number}}\" }"
            }
        }.to_json
      }
    ))
    response.parsed_response
  end

  def get_list()
    puts("GET LIST")
    list_uri = @@base_uri + '/gateways/' + ENV['GATEWAY_TOKEN'] + '/transactions.json?order=desc'
    response = HTTParty.get(list_uri, base_options)
    response.parsed_response
  end

  private def base_options
    {
      headers: {
        'Content-Type' => 'application/json'
      },
      basic_auth: {
        username: ENV['SPREEDLY_ENV_KEY'],
        password: ENV['SPREEDLY_SECRET']
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def destroy
        token = params[:id]
        success = CardManager.new().redact_card(token)
        redirect_to flights_path
     end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.order(:origin)
    @saved_cards = CardManager.new().get_saved_cards['payment_methods']
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    def index
        @transaction_list = Purchaser.new().get_list()['transactions'].each { |v| v['created_at'] = Date.parse v['created_at'] }
        @filtered_list = @transaction_list.select{|x| ['Purchase', 'DeliverPaymentMethod'].include? x['transaction_type']}
    end

    def create
        save_card = params[:save_card] === 'true'
        use_expedia = params[:use_expedia] === 'true'
        token = params[:token]
        amount = params[:price].to_i
        
        if use_expedia
            success = Purchaser.new().purchase_external(token, amount)
            if success && success['transaction']['succeeded'] == true
                flash['success'] = 'Your purchase was successfully delivered!'
                redirect_to flights_path
            else
                flash['alert'] = success['transaction']['message']
                redirect_to flights_path
            end
        else
            success = Purchaser.new().purchase_gateway(token, amount, save_card)
            if success && success['transaction']['succeeded'] == true
                flash['success'] = 'Your purchase was successful!'
                redirect_to flights_path
            else
                flash['alert'] = success['transaction']['message']
                redirect_toflights_path
            end
        end

     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
    def flash_class(level)
        case level
        when "notice"
            "alert alert-info"
        when "success"
            "alert alert-success"
        when "error"
            "alert alert-danger"
        when "alert"
            "alert alert-danger"
        else
            "alert alert-danger"
        end
    end
end

app/views/flights/index.html.erb
<div class="container">
  </br>
  <div>
    <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
        </div>
    <% end %>
  </div>

  <h1>Spreedly Airlines Flights</h1>
  </br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Origin</th>
        <th scope="col">Destination</th>
        <th scope="col">Price</th>
        <th scope="col">Checkout Options: <small>Save Card <%=check_box_tag 'save_card', '0', false, id: 'save_card_check'%>
                                                 Use Expedia Checkout <%=check_box_tag 'use_expedia', '0', false, id: 'use_expedia_check'%></small></th>
      </tr>
    </thead>

    <tbody>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.origin %></td>
          <td><%= flight.destination %></td>
          <td><%= number_to_currency(flight.price/100) %></td>
          <td style="text-align:center"><button class='btn btn-primary' 
              onClick='openExpress("<%= number_to_currency(flight.price/100) %>", <%= flight.price %>, "<%= flight.origin %>", "<%= flight.destination %>", <%= flight.id %>)'>Purchase With New Card</button>
              <button class='btn btn-primary' data-toggle="modal" data-target="#cardsModal" data-price=<%= flight.price %>>Use Saved Card</button></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="modal fade" id="cardsModal" tabindex="-1" role="dialog" aria-labelledby="cardsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cardsModalLabel">Saved Cards</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table id="cardsTable" class="table table-sm">
        <span id="price-tag"></span>
        <thead>
            <tr>
            <th scope="col">Card Type</th>
            <th scope="col">Last Four</th>
            <th scope="col"></th>
            <th scope="col"></th>
            </tr>
        </thead>

        <tbody>
            <% @saved_cards.each do |item| %>
                <tr>
                    <td><%= item["card_type"].gsub("_", " ").capitalize! %></td>
                    <td><%= item["last_four_digits"] %></td>
                    <td><button type="button" class="btn btn-success btn-xs" onClick='useSavedCard("<%= item["token"] %>")'>Use This Card</button></td>
                    <td><%= link_to 'Forget This Card', card_path(item['token']), method: :delete %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

  <%= form_tag transactions_url, id: 'payment-form' do %>
    <%= hidden_field_tag :price, nil, id: 'charge-price' %>
    <%= hidden_field_tag :token, nil, id: 'payment-method-token' %>
    <%= hidden_field_tag :save_card, false, id: 'save-card' %>
    <%= hidden_field_tag :use_expedia, false, id: 'use-expedia' %>
  <% end %>

  <br>
  <%= link_to 'Past Transactions', transactions_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreedlyAirlines</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://core.spreedly.com/iframe/express-2.min.js" id="express-script"></script>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<div class="container">
    </br>
    <div class="col-sm-offset-5 col-sm-2">
        <%= link_to 'Back', flights_path, class: "btn btn-primary btn-block" %>
    </div>
    </br>
    <p><h1>Recent Transactions</h1>(Excluding Expedia)</p>

    <table id="transactionTable" class="table table-striped table-bordered table-sm">
        <thead>
            <tr>
            <th scope="col">Date</th>
            <th scope="col">User</th>
            <th scope="col">Amount</th>
            <th scope="col">Status</th>
            <th scope="col">Details</th>
            <th scope="col">Last Four</th>
            </tr>
        </thead>

        <tbody>
            <% @filtered_list.each do |item| %>
                <tr>
                    <td><%= item["created_at"] %></td>
                    <td><%= item["payment_method"]["full_name"] %></td>
                    <td><%= number_to_currency(item["amount"].to_f/100) %></td>
                    <td><%= item["message"] %></td>
                    <td><%= item["state"] %></td>
                    <td><%= item["payment_method"]["last_four_digits"] %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>